CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now()
); 

ALTER TABLE recipes
  ADD COLUMN
    author_id INTEGER REFERENCES users(id)
    ON DELETE SET NULL;

ALTER TABLE categories 
  ADD COLUMN
    author_id INTEGER REFERENCES users(id)
    ON DELETE SET NULL;


    INSERT INTO users (id, user_name, password, date_created, date_modified)
VALUES 
-- all passwords are 'Password1!'
(1,'user1@gmail.com', '$2a$10$do9aqSHBEOX2mmidBFxxPOdknoul45m.TDoeQkdumVNrEkF2sn3KK', '2020-03-22T16:28:32.615Z','2020-03-22T16:28:32.615Z'),
(2,'user2@gmail.com', '$2a$10$4AGfWWmypn45VHgsdyMOY.xymoQInQIwtzbFWeyvUvWVknpeSWwki', '2020-03-22T16:28:32.615Z','2020-03-22T16:28:32.615Z'),
(3,'user3@gmail.com', '$2a$10$XrZZWlImZXIhAIf7b.8xqeDNK6kDU81An9lU.XzsuvgtR7hyG43fm', '2020-03-22T16:28:32.615Z','2020-03-22T16:28:32.615Z');

-- ensures id generator will start from the max id num in database
-- instead of starting at 1
SELECT setval('users_id_seq', (SELECT MAX(id) from "users"));

INSERT INTO categories (id,category_name,author_id)
VALUES 
(1,'user1s category1',1),
(2,'user1s category2',1),
(3,'user2s category',2),
(4,'user3s category',3);

INSERT INTO recipes (id,title, description, ingredients, directions, date_created, date_modified,category_id,author_id)
VALUES 
(1,'user1s recipe1 for category1',
 'user1s recipe1 for category1',
 'user1s recipe1 for category1',
 'user1s recipe1 for category1', 
 '2023-03-22T16:28:32.615Z', 
 '2023-03-22T16:28:32.615Z',
 1,
 1),
 (2,'user1s recipe2 for category1',
 'user1s recipe2 for category1',
 'user1s recipe2 for category1',
 'user1s recipe2 for category1', 
 '2023-03-22T16:28:32.615Z', 
 '2023-03-22T16:28:32.615Z',
 1,
 1),
 (3,'user1s recipe3 for category2',
 'user1s recipe3 for category2',
 'user1s recipe3 for category2',
 'user1s recipe3 for category2', 
 '2023-03-22T16:28:32.615Z', 
 '2023-03-22T16:28:32.615Z',
 2,
 1),
(4,'user2s recipe for category2', '2','2','2', '2023-03-22T16:28:32.615Z', '2023-03-22T16:28:32.615Z',3,2),
(5,'user3s recipe for category3', '3','3','3', '2023-03-22T16:28:32.615Z', '2023-03-22T16:28:32.615Z',4,3);

SELECT setval('recipes_id_seq', (SELECT MAX(id) from "recipes"));
SELECT setval('categories_id_seq', (SELECT MAX(id) from "categories"));